# Generated by Django 3.0 on 2020-01-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('sdate', models.DateField()),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
