# Generated by Django 3.0.2 on 2020-02-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guitars', '0002_guitars_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitars',
            name='quantity',
        ),
    ]
